apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-cicd-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-cicd
  template:
    metadata:
      labels:
        app: maven-cicd
    spec:
      containers:
      - name: maven-cicd-container
        image: datapandassandbox/maven-web-app-contanerized-cicd:10
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven-cicd-service
  namespace: default
spec:
  selector:
    app: maven-cicd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
